version: "3.8"

services:

  # ipfs-image:
  #   # image: ipfs/go-ipfs:latest
  #   image: local/go-ipfs:v0.7.0-docker
  #   build:
  #     # context: https://github.com/go-ipfs.git#v0.7.0-docker:.
  #     context: https://github.com/go-ipfs.git#aeeeca9ff5ad47283537d0a18ed68d86be707e2b
  #     dockerfile: ./Dockerfile

  ubuntu20-openjdk-clj-lein-node:
    image: local.ubuntu20-openjdk-clj-lein-node
    build:
      context: ./images/ubuntu20-openjdk-clj-lein-node
      dockerfile: ./Dockerfile

  openjdk-jdk11-clj-lein:
    image: local.openjdk-jdk11-clj-lein
    build:
      context: ./images/openjdk-jdk11-clj-lein
      dockerfile: ./Dockerfile

  openjdk-jre11-clj-lein:
    image: local.openjdk-jre11-clj-lein
    build:
      context: ./images/openjdk-jre11-clj-lein
      dockerfile: ./Dockerfile

  openjdk-jdk11-clj-lein-node:
    image: local.openjdk-jdk11-clj-lein-node
    build:
      context: ./images/openjdk-jdk11-clj-lein-node
      dockerfile: ./Dockerfile

  adoptopenjdk-ubuntu-jdk14-openj9:
    image: local.adoptopenjdk-ubuntu-jdk14-openj9
    build:
      context: ./images/adoptopenjdk-ubuntu-jdk14-openj9
      dockerfile: ./Dockerfile

  jvm-prod-builder:
    image: local.jvm-prod-builder
    build:
      context: ./images/jvm-prod
      dockerfile: ./builder.Dockerfile
      args:
        - BASE_IMAGE=local.openjdk-jdk11-clj-lein
    depends_on:
      - openjdk-jdk11-clj-lein

  jvm-prod-runner:
    image: local.jvm-prod-runner
    build:
      context: ./images/jvm-prod
      dockerfile: ./runner.Dockerfile
      args:
        - BASE_IMAGE=openjdk:11.0.7-jre-slim-buster@sha256:34d0f8555c4a9dcf13ac16c40f71582e891d6552e47a96c833caa14cd1fbe18a
        # - BASE_IMAGE=adoptopenjdk/openjdk11-openj9:jre-11.0.7_10_openj9-0.20.0-alpine@sha256:e1932115bff763cc9aebfe50301b322b9e7873f53347279e774b50cc1e5f2581

  ui-prod-builder:
    image: local.ui-prod-builder
    build:
      context: ./images/ui-prod
      dockerfile: ./builder.Dockerfile
      args:
        - BASE_IMAGE=local.openjdk-jdk11-clj-lein-node
    depends_on:
      - openjdk-jdk11-clj-lein-node

  ui-prod-runner:
    image: local.ui-prod-runner
    build:
      context: ./images/ui-prod
      dockerfile: ./runner.Dockerfile
      args:
        - BASE_IMAGE=nginx:stable-alpine@sha256:676b8117782d9e8c20af8e1b19356f64acc76c981f3a65c66e33a9874877892a