#!/bin/bash


coder(){
  # docker run -it --name code-server -p 127.0.0.1:8080:8080 \
  #   -v "$HOME/.config:/home/coder/.config" \
  #   -v "$PWD:/home/coder/project" \
  #   -u "$(id -u):$(id -g)" \
  #   -e "DOCKER_USER=$USER" \
  #   codercom/code-server:latest
  docker run -it --rm --name code-server -p 127.0.0.1:8080:8080 \
    -u "$(id -u):$(id -g)" \
    -e "DOCKER_USER=$USER" \
    codercom/code-server:latest --auth none
}


"$@"